name: OS Unit Tests

on:
  push:
    branches:
      - staging
      - trying

jobs:
  test-os:
    runs-on: ${{ matrix.os }}
    matrix:
      os: [ubuntu-latest, windows-latest, macos-latest]
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v2.2.0

    - name: Set up Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: 1.4

    - name: Install Project Packages
      run: |
        julia --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.build()'

    - name: Build System Image
      run: |
        julia --project=@. .dev/systemimage/climate_machine_image.jl ClimateMachine.so true

    - name: Run Unit Tests
      run: |
        julia --project=@. -J ClimateMachine.so -e 'using Pkg; Pkg.test()'
